### ISSUE TITLE
ATT Not displayed for 15.4.1 (Mar 31 release)

### ISSUE THREAD

**Issue by mrbrannan** [deniza/app_tracking_transparency#29]
We usually pass App Store submission but just failed on our latest today.

> We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.4.1

**Comment by WiliamGP** [comment]
Hi @mrbrannan did you manage to solve the problem?  If so could you tell me how you did it please. Thanks.
Best Regards

**Comment by klivin** [comment]
This also happened to us. Annnnd you closed with no additional comment?

**Comment by psovit** [comment]
Same here...

**Comment by WiliamGP** [comment]
Hi @klivin and @psovit, I managed to fix the problem with the tip I saw in another post here, using Future.delayed(); with 1 second.

Here the example:

```
Future.delayed(
      Duration(seconds: 1),
      () {
        AppTrackingTransparency.requestTrackingAuthorization().then(
          (value) async {
            ...
          },
        );
      },
    );
```

**Comment by deniza** [comment]
I guess this happens because you also try to display notification permission dialog which cancels tracking authorization dialog. (you cannot show more than one native dialog).

To solve this problem I highly recommend showing a custom explainer dialog before triggering actual native tracking dialog. Please check the example for a sample use case.
