### ISSUE TITLE
Override tracking status

### ISSUE THREAD

**Issue by AntoniPochopien** [deniza/app_tracking_transparency#42]
In my case I would like to give user opportunity to reset ad consent, but with this package I can display dialog only once if user was already asked.

**Comment by deniza** [comment]
Once a user has given their consent to App Tracking Transparency (ATT), there is no way to display the ATT dialog again. This is by design from Apple. If you would like users to change their consent, you can provide them with instructions on how to do so manually. To do this, you can direct them to the Settings app on their device, where they can go to Privacy > Tracking and change their consent for each app individually.
